[package]
name = "onedot-bundler"
version = "0.1.0"
edition = "2021"

[dependencies]
swc = "0.224.0"
swc_common = "0.29.0"
swc_ecma_parser = "0.122.0"
swc_ecma_transforms = "0.202.0"
swc_ecma_codegen = "0.122.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
