[package]
name = "onedot_bundler"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
swc_common = "0.33"
swc_ecma_parser = "0.141"
swc_ecma_ast = "0.110"
swc_ecma_visit = "0.99"
serde = { version = "1", features=["derive"] }
serde_json = "1"
regex = "1"
once_cell = "1"
