[package]
name = "onedot_native"
version = "1.0.0"
edition = "2021"
authors = ["ONEDOT Team"]
description = "Native rendering engine with Skia GPU acceleration and JSI bridge"
license = "MIT"
repository = "https://github.com/onedot-js/onedot"

[lib]
name = "onedot_native"
crate-type = ["cdylib", "staticlib"]

[dependencies]
skia-safe = { version = "0.65", features = ["gl", "vulkan", "metal"] }
jni = "0.21"
ndk = "0.8"
winapi = { version = "0.3", features = ["winuser", "wingdi", "d3d11"] }
cocoa = "0.25"
x11 = { version = "2.21", features = ["xlib", "xinput2"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
crossbeam-channel = "0.5"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
ndk-context = "0.1"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"
block = "0.1"

[build-dependencies]
cbindgen = "0.24"
